name: ColorfulArmor
version: 2.0
main: Enes5519\colorfularmor\ColorfulArmor
api: 3.0.0
author: Enes5519

permissions:
  enes5519.colorfularmor:
    default: op
    description: ColorfulArmor Permission